<a href="https://colab.research.google.com/github/sadarshs/dayPython/blob/main/Project3_ICT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [2]:
import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('1774404110.csv')

df.head()

Saving 1774404110.csv to 1774404110 (1).csv

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [ ]:
mpg = df['mpg'].to_numpy()

print("Mean:", np.mean(mpg))
print("Median:", np.median(mpg))
print("Std Dev:", np.std(mpg))
print("MPG > 25:", np.sum(mpg > 25))

Mean: 23.514572864321607
Median: 23.0
Std Dev: 7.806159061274433
MPG > 25: 158

In [3]:
cars = df[df['cylinders'] > 6]['car name'].tolist()
print(cars)

['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino', 'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii', 'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se', "plymouth 'cuda 340", 'chevrolet monte carlo', 'buick estate wagon (sw)', 'ford f250', 'chevy c20', 'dodge d200', 'hi 1200d', 'chevrolet impala', 'pontiac catalina brougham', 'ford galaxie 500', 'plymouth fury iii', 'dodge monaco (sw)', 'ford country squire (sw)', 'pontiac safari (sw)', 'chevrolet impala', 'pontiac catalina', 'plymouth fury iii', 'ford galaxie 500', 'amc ambassador sst', 'mercury marquis', 'buick lesabre custom', 'oldsmobile delta 88 royale', 'chrysler newport royal', 'amc matador (sw)', 'chevrolet chevelle concours (sw)', 'ford gran torino (sw)', 'plymouth satellite custom (sw)', 'buick century 350', 'amc matador', 'chevrolet malibu', 'ford gran torino', 'dodge coronet custom', 'mercury marquis brougham', 'chevrolet caprice classic', 'ford ltd', 'plymouth fury gran sedan', 'chrysler new yorker brougham', 'buick electra 225 custom', 'amc ambassador brougham', 'chevrolet impala', 'ford country', 'plymouth custom suburb', 'oldsmobile vista cruiser', 'chevrolet monte carlo s', 'pontiac grand prix', 'dodge dart custom', 'oldsmobile omega', 'ford gran torino', 'buick century luxus (sw)', 'dodge coronet custom (sw)', 'ford gran torino (sw)', 'amc matador (sw)', 'pontiac catalina', 'chevrolet bel air', 'plymouth grand fury', 'ford ltd', 'chevrolet monza 2+2', 'ford mustang ii', 'chevrolet chevelle malibu classic', 'dodge coronet brougham', 'amc matador', 'ford gran torino', 'plymouth volare premier v8', 'cadillac seville', 'chevy c10', 'ford f108', 'dodge d100', 'chevrolet caprice classic', 'oldsmobile cutlass supreme', 'dodge monaco brougham', 'mercury cougar brougham', 'pontiac grand prix lj', 'chevrolet monte carlo landau', 'chrysler cordoba', 'ford thunderbird', 'oldsmobile cutlass salon brougham', 'dodge diplomat', 'mercury monarch ghia', 'chevrolet monte carlo landau', 'ford futura', 'dodge magnum xe', 'chevrolet caprice classic', 'ford ltd landau', 'mercury grand marquis', 'dodge st. regis', 'buick estate wagon (sw)', 'ford country squire (sw)', 'chevrolet malibu classic (sw)', 'chrysler lebaron town @ country (sw)', 'cadillac eldorado', 'oldsmobile cutlass salon brougham', 'oldsmobile cutlass ls']

In [4]:
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

hp = df['horsepower'].to_numpy()

hp = np.where(np.isnan(hp), np.nanmean(hp), hp)

hp_updated = hp * 1.10

print(hp_updated[:10])

[143.  181.5 165.  165.  154.  217.8 242.  236.5 247.5 209. ]

In [5]:
disp = df['displacement'].to_numpy()
origin = df['origin'].to_numpy()

avg_disp = np.mean(disp[origin == 2])
print(avg_disp)

109.14285714285714

In [6]:
cyl = df['cylinders'].to_numpy()
mpg = df['mpg'].to_numpy()

for c in np.unique(cyl):
    print(f"{c} cylinders →", np.mean(mpg[cyl == c]))

3 cylinders → 20.55
4 cylinders → 29.28676470588235
5 cylinders → 27.366666666666664
6 cylinders → 19.985714285714284
8 cylinders → 14.963106796116506

PANDAS

In [7]:
print(df.head(10))
print("Shape:", df.shape)
print(df.describe())

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5
5  15.0          8         429.0       198.0    4341          10.0
6  14.0          8         454.0       220.0    4354           9.0
7  14.0          8         440.0       215.0    4312           8.5
8  14.0          8         455.0       225.0    4425          10.0
9  15.0          8         390.0       190.0    3850           8.5

   model year  origin                   car name
0          70       1  chevrolet chevelle malibu
1          70       1          buick skylark 320
2          70       1         plymouth satellite
3          70       1              amc rebel sst
4          70       1                ford torino
5          70       1           ford galaxie 500
6          70       1           chevrolet impala
7          70       1          plymouth fury iii
8          70       1           pontiac catalina
9          70       1         amc ambassador dpl
Shape: (398, 9)
              mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000
mean    23.514573    5.454774    193.425879  104.469388  2970.424623
std      7.815984    1.701004    104.269838   38.491160   846.841774
min      9.000000    3.000000     68.000000   46.000000  1613.000000
25%     17.500000    4.000000    104.250000   75.000000  2223.750000
50%     23.000000    4.000000    148.500000   93.500000  2803.500000
75%     29.000000    8.000000    262.000000  126.000000  3608.000000
max     46.600000    8.000000    455.000000  230.000000  5140.000000

       acceleration  model year      origin
count    398.000000  398.000000  398.000000
mean      15.568090   76.010050    1.572864
std        2.757689    3.697627    0.802055
min        8.000000   70.000000    1.000000
25%       13.825000   73.000000    1.000000
50%       15.500000   76.000000    1.000000
75%       17.175000   79.000000    2.000000
max       24.800000   82.000000    3.000000

In [8]:
filtered = df[(df['model year'] == 75) & (df['weight'] < 3000)]

result = filtered[['car name', 'weight', 'mpg']]
print(result)

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

In [9]:
print(df.isnull().sum())

df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [10]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,power_to_weight_ratio
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu,0.037100
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320,0.044679
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite,0.043655
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst,0.043694
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino,0.040591

In [ ]:
print(df.groupby('origin')['mpg'].mean())

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

In [ ]:
summary = df.groupby('model year')[['mpg','weight','horsepower']].mean()
print(summary)

                  mpg       weight  horsepower
model year
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

In [14]:
high_mpg = df[df['mpg'] > 30][['mpg','cylinders','horsepower','weight']]

high_mpg.to_csv('high_mpg_cars.csv', index=False)

In [12]:
from google.colab import files
files.download('high_mpg_cars.csv')